baseURL = "https://zaxrmdn.github.io/myblog/"
languageCode = "en-us"
title = "My Blog"
theme = "ananke"
[menu]
  [[menu.main]]
  name = "About"
  url = "/bio/"
  weight = 2
  
  [params]
  bio = "Hello! I'm [Your Name], a passionate tech enthusiast and web developer. I love working on open-source projects and sharing my knowledge through blogging."
