site_name: My Blog
site_description: Tech Notes, Tutorials, and Personal Documentation
theme:
  name: material
nav:
  - Beranda: index.md
  - Artikel:
      - Panduan Pertama: docs/panduan-pertama.md
      - Tips dan Trik: docs/tips-trik.md

